@startuml

title Usecase for Information system

' left to right direction

actor Споживач
actor Адміністратор
actor :Сервіс Е-Pay:

Адміністратор -|> Споживач 

rectangle Software {

    usecase (E-сплата)
    usecase (Арендувати житло)
    usecase (Авторизувати користувача)
    usecase (Отримати список користувачів)
    
    (Отримати список користувачів) .> (Авторизувати користувача) : include
    (E-сплата) .> (Арендувати житло) : extends
    (Арендувати житло) .> (Авторизувати користувача) : include

    Споживач -- (Авторизувати користувача)
    Споживач -- (Арендувати житло)
    Адміністратор -- (Отримати список користувачів)
    :Сервіс Е-Pay: -- (E-сплата)

}

@enduml
